### PR TITLE
MODIS download

### PR DESCRIPTION
**Pull request by ashiklom**
GPP isn't available for the years we want, but FPAR and LAI is -- we can start with those. If we can, I might also try to estimate MODIS fluorescence from the ocean bands, though that will be harder because I have to manually locate the sites and stuff.

### CODE REVIEW

**Comment by bcow** [comment]
Looks good to me - let's merge it in so I can add to it. 
@mdietze I don't seem to have privileges to merge pull requests

**Comment by ashiklom** [comment]
Since I have the go-ahead, I'm gonna merge this on @bcow's behalf.

**Comment by bcow** [comment]
:cow: mooo thanks

**Comment by mdietze** [comment]
@bcow that would be because you never accepted the Github invitation to join the GPP team

**Pull request merged**
